# Generated by Django 3.1.12 on 2022-02-18 15:24

from django.db import migrations, models

from integration import error_codes

gateway_timeout_error = {
    'code': error_codes.GATEWAY_TIMEOUT,
    'error': 'GATEWAY_TIMEOUT_ERROR',
    'default_wizard_message': '',
    'failure_reason_mail': 'This site can’t be reached. It took too long to respond.',
    'send_email': False,
    'description': 'This site can’t be reached. It took too long to respond',
}


def add_gateway_error_catalogue(apps, _):
    error_catalogue_model = apps.get_model('integration', 'ErrorCatalogue')

    error_catalogue_model.objects.create(**gateway_timeout_error)


class Migration(migrations.Migration):
    dependencies = [
        ('integration', '0045_add_user_input_error'),
    ]
    operations = [
        migrations.AlterField(
            model_name='connectionaccount',
            name='error_code',
            field=models.CharField(
                choices=[
                    ('000', 'None'),
                    ('001', 'Other'),
                    ('002', 'Insufficient Permissions'),
                    ('003', 'Missing Github Organization'),
                    ('004', 'Denial Of Consent'),
                    ('005', 'Insufficient Config Data'),
                    ('006', 'Invalid Client Credentials'),
                    ('007', 'AWS error'),
                    ('008', 'Expired account'),
                    ('009', 'Azure error'),
                    ('010', 'Google Cloud (GCP) error'),
                    ('011', 'Provider Server Error'),
                    ('012', 'Resource not found'),
                    ('013', 'API call exceeded rate limit due to too many requests'),
                    ('014', 'Github App is not installed on the organization'),
                    ('015', 'Provider Graphql API Error'),
                    ('016', 'Connection Time Out'),
                    ('017', 'Default GraphQL Error'),
                    ('018', 'Access Revoked'),
                    ('019', 'The user entered an invalid value'),
                    ('018', 'Access Revoked'),
                    ('020', 'Gateway Timeout'),
                ],
                default='000',
                max_length=20,
            ),
        ),
        migrations.RunPython(add_gateway_error_catalogue),
    ]
