# Generated by Django 3.2.15 on 2022-09-25 22:25

from django.db import migrations, models

from integration import error_codes

service_unavailable_error = {
    'code': error_codes.SERVICE_UNAVAILABLE,
    'error': 'SERVICE_UNAVAILABLE',
    'default_wizard_message': '',
    'failure_reason_mail': '',
    'send_email': False,
    'description': 'Server is not ready to handle the request',
}


def add_service_unavailable_error_catalogue(apps, _):
    error_catalogue_model = apps.get_model('integration', 'ErrorCatalogue')

    error_catalogue_model.objects.create(**service_unavailable_error)


class Migration(migrations.Migration):
    dependencies = [
        ('integration', '0061_add_datadog_alert_for_invalid_credentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionaccount',
            name='error_code',
            field=models.CharField(
                choices=[
                    ('000', 'None'),
                    ('001', 'Other'),
                    ('002', 'Insufficient Permissions'),
                    ('003', 'Missing Github Organization'),
                    ('004', 'Denial Of Consent'),
                    ('005', 'Insufficient Config Data'),
                    ('006', 'Invalid Client Credentials'),
                    ('007', 'Expired Token'),
                    ('011', 'Provider Server Error'),
                    ('012', 'Resource not found'),
                    ('013', 'API call exceeded rate limit due to too many requests'),
                    ('014', 'Github App is not installed on the organization'),
                    ('015', 'Provider Graphql API Error'),
                    ('016', 'Connection Time Out'),
                    ('017', 'Default GraphQL Error'),
                    ('018', 'Access Revoked'),
                    ('019', 'The user entered an invalid value'),
                    ('020', 'Gateway Timeout'),
                    ('008', 'Bad Gateway'),
                    ('021', 'Bad request syntax or unsupported method'),
                    ('009', 'Service Unavailable'),
                ],
                default='000',
                max_length=20,
            ),
        ),
        migrations.RunPython(add_service_unavailable_error_catalogue),
    ]
